services:
  - type: web
    runtime: static
    name: laff-british-school-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: true
