services:
  - type: web
    runtime: node
    name: laff-british-school-backend
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
